### ISSUE TITLE
Oblíbené písně

### ISSUE THREAD

**Issue by jridky** [proscholy/proscholy-flutter#4]
Přišlo hlášení od uživatele:

> Když si dám nějakou píseň do oblíbených, tak tam chvíli vydrží, ale za den, nebo dva zmizí a mám v oblíbených zase prázdno.

**Comment by Paprikadobi** [comment]
Při aktualizace písně docházelo k přepsání všech jejich parametrů. 
Opraveno v: 4c8db50cb2218d7b8e9ca3b7d6aae8cdf35b764b
