### ISSUE TITLE
Automatic releases using fastlane

### ISSUE THREAD

**Issue by Paprikadobi** [proscholy/proscholy-flutter#40]
Toto by možná mohlo být zajímavé vyzkoušet, určitě by to ulehčilo hodně práce. https://fastlane.tools

**Comment by michaeldojcar** [comment]
Vypadá dobře. :-) To je package do lokálu nebo služba?

**Comment by Paprikadobi** [comment]
To nevím, kdysi dávno jsem o tom slyšel, že se to docela používá a dneska jsme na to nějak narazili s kámošem, tak jsem to sem jen hodil, abych si na to třeba někdy vzpomněl.
