### ISSUE TITLE
Nezobrazuje se text písně

### ISSUE THREAD

**Issue by michaeldojcar** [proscholy/proscholy-flutter#42]
Verze: TestFlight 3.0.0 (1)

Když otevřít libovolnou píseň, neukáže se mi její obsah, pouze navbar a navigace. Je to očekávaný stav?

![image](https://user-images.githubusercontent.com/1665018/176354021-826ed244-0986-4c2d-ad70-d36f27e5b766.png)

**Comment by Paprikadobi** [comment]
Čekal jsem, že bude nějaký problém na androidu, ale u iOS jsem to nečekal. Mi se všechny písně zobrazují normálně v simulátoru i na fyzickém iPhonu, tak by mě zajímalo čím to je.

**Comment by michaeldojcar** [comment]
Po odinstalaci a instalaci už to jede. Možná migrace dat z ostré verze na betu?

**Comment by Paprikadobi** [comment]
No mi se to nedělo ani při tom přechodu ze staré verze, ale už jsem to asi našel. Vypadá to, že nějakou část při načítání ne awaitnu a když postupuješ moc rychle, tak ty data ještě v databázi nejsou.
