### ISSUE TITLE
Debug hláška: Got here from null

### ISSUE THREAD

**Issue by michaeldojcar** [proscholy/proscholy-flutter#47]
V beta 3.0.0(5) se mi ukazuje toto.

![image](https://user-images.githubusercontent.com/1665018/178421037-52a7bb57-32bf-42d6-b0a3-be55f8fbdda4.png)

**Comment by Paprikadobi** [comment]
To jsem si tam přidal pro ověření těch applinků, ale zjistil jsem, že to půjde testovat až na produkční verzi. V další verzi už to tam nebude :)

**Comment by michaeldojcar** [comment]
Chápu. :)
