### ISSUE TITLE
Stylování komentářů

### ISSUE THREAD

**Issue by michaeldojcar** [proscholy/proscholy-flutter#50]
Zkusil bych dát komentáře do barvy #827C7C.
Mimochodem není ta kurzíva nějak moc zkosená?
Ve Figmě jsme dávali Roboto v kurzívě vypadá to mnohem míň zkoseně. :-)

**Comment by Paprikadobi** [comment]
Podívám se na to, chtěl bych během dneška vyladit už všechny ty barvy a styly, hlavně v dark módu, kde jsem to zatím vůbec neřešil.

**Comment by michaeldojcar** [comment]
Jj, těším se. :-)
