### ISSUE TITLE
Při kliknutí na novinky aplikace crashne

### ISSUE THREAD

**Issue by michaeldojcar** [proscholy/proscholy-flutter#54]
OS: iOS 16 beta
Verze: 3.0.0(6) 

Stačí kliknout na aktualitu a appka okamžitě spadne.

**Comment by Paprikadobi** [comment]
Očekávám, že url u novinky je nějaký String. Co by se mělo stát po kliknutí, pokud tam url není?

**Comment by michaeldojcar** [comment]
A není tam? Na webu to normálně odkazuje.
Jinak, kdyby tam hypoteticky nebyl odkaz, tak by to nemělo dělat asi nic.

**Comment by Paprikadobi** [comment]
Aha, dívám se, že link tam je, ale není to https, zjistím co se s tím dá dělat.
