### ISSUE TITLE
Když na tabletu přejdu z homescreenu na search, neschová se původní input

### ISSUE THREAD

**Issue by michaeldojcar** [proscholy/proscholy-flutter#60]
<img width="1180" alt="image" src="https://user-images.githubusercontent.com/1665018/179719562-0c7d9555-2909-403f-b512-286b835067c0.png">

**Comment by Paprikadobi** [comment]
A to máš tu poslední betu? Tam už by se to skrývat mělo nebo aspoň v simulátoru se to skrývá.

**Comment by michaeldojcar** [comment]
TestFlight 3.0.0 (21)
Ale děje se mi to jenom při searchi z homescreenu, když pak zanořím do písně a vrátím se, tak se to schová.
