### ISSUE TITLE
Nelze připnout papírový zpěvník na mobilu

### ISSUE THREAD

**Issue by michaeldojcar** [proscholy/proscholy-flutter#81]
Na mobilu nejde připnout papírový Zpěvník podobně jako to lze na tabletu.

Chtělo by to zamyslet se nad návrhem, jak by to vypadalo hezky. Otázka, zda by tomu neslušely taky ty loga zpěvníků jako byly dřív na mobilu a teď jsou jen na tabletu. :-)

**Comment by vitkolos** [comment]
Jejda, teď se dívám, že mi to v návrhu ve Figmě chybí. Představoval bych si to prakticky tak jako doposud (ve staré verzi appky), akorát zpěvníky nebudou mít vlastní odkaz dole v menu, ale budou dostupné přes homepage (kliknutím na zobrazit více na tom „widgetu“) a přes filtry (chtěl bych tam umístit tlačítko, které uživatele odkáže na stránku se zpěvníky). Co se týče widgetu na homepage, tak tam počítám jenom se čtverečky v barvě zpěvníku – viz Figma. Myslím, že by ten widget měl vypadat stejně jak na mobilu, tak na tabletu. Lišit se bude jenom rozmístění widgetů (ve více sloupcích).

Co se týče připínání, tak tam bych funkcionalitu taky zachoval, připnutí zpěvníků se projeví na homepage, ve filtrech a ve štítcích u písní.
